version: '3'

services:
  app:
    environment:
      - ENVIRONMENT=
      - PORT=
      - HOST_DB=
      - PORT_DB=
      - USER_DB=
      - PASS_DB=
      - DATA_DB=
      - CLIENT_DB=
      - MAX_POOL_DB=
      - MIN_POOL_DB=
    container_name: app
    build: .
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - .:/usr/app
