version: '3.1'
services:
  app:
    image: node:alpine
    container_name: backend
    volumes:
      - ../:/workspace/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"
    expose:
      - "3000"
